spring.application.name=2400031981_exp6
spring.datasource.url=jdbc:mysql://localhost:3306/fsad6exp
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect